[package]
name = "kopuz-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true

[lib]
name = "proto"

[lints]
workspace = true

[dependencies]
api = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
protox = { workspace = true }
prost = { workspace = true }
